__all__ = [
    "FilterRunner",
]

import typing

from filters.base import BaseFilter, BaseFilterError, FilterHarness, UncaughtException


class FilterRunner[T](FilterHarness):
    """
    Wrapper for a filter that provides an API like what you would expect from a Django
    form — at least, when it comes to methods related to data validation 0:)
    """

    def __init__(
        self,
        filter_: BaseFilter[T],
        data: typing.Any = None,
    ) -> None:
        super().__init__()

        self.data: typing.Any = data

        self.filter: BaseFilter[T] = BaseFilter.resolve(filter_)
        self.filter.harness = self

        self._cleaned_data: T | None = None
        self._filter_errors: dict[str, list[BaseFilterError]] = {}
        self._has_exceptions: bool = False

    def __str__(self) -> str:
        return str(self.filter)

    def apply(self, incoming_data: typing.Any) -> None:
        """
        Runs the filter chain against a value.
        """
        self.data = incoming_data
        self._cleaned_data = None

    @property
    def cleaned_data(self) -> T | None:
        """
        Returns the resulting value after applying the request filter.
        """
        self.full_clean()
        return self._cleaned_data

    @property
    def errors(self) -> dict[str, list[dict[str, str]]]:
        """
        Returns a dict of error messages generated by the Filter, in a format suitable
        for inclusion in e.g. a 400 Bad Request response payload.

        Example:

        .. code-block:: python

            {
                'authToken': [
                    {
                        'code': 'not_found',
                        'message': 'No AuthToken found matching this value.',
                    },
                ],

                'data.foobar': [
                    {
                        'code': 'unexpected',
                        'message': 'Unexpected key "foobar".',
                    },
                ],
            }
        """
        return {
            key: [
                {
                    "code": str(e.code),
                    "message": str(e),
                }
                for e in errors
            ]
            for key, errors in self.filter_errors.items()
        }

    @property
    def error_codes(self) -> typing.Dict[
        typing.Text,
        typing.List[typing.Text],
    ]:
        """
        Returns a dict of error codes generated by the Filter.
        """
        return {
            key: [str(e.code) for e in errors]
            for key, errors in self.filter_errors.items()
        }

    @property
    def has_exceptions(self) -> bool:
        """
        Returns whether any unhandled exceptions occurred while filtering the
        value.
        """
        self.full_clean()
        return self._has_exceptions

    @property
    def filter_errors(self) -> dict[str, list[BaseFilterError]]:
        """
        Returns the raw FilterMessages that were generated by the Filter.
        """
        self.full_clean()
        return self._filter_errors

    def is_valid(self) -> bool:
        """
        Returns whether the request payload successfully passed the Filter.
        """
        return not self.filter_errors

    def full_clean(self) -> None:
        """
        Applies the filter to the request data.
        """
        self._filter_errors = {}
        self._has_exceptions = False

        self._cleaned_data = self.filter.apply(self.data)

    def handle_filter_error(self, e: BaseFilterError) -> None:
        """
        Handles an error raised by the filter.
        """
        key = e.filter.key
        if key not in self._filter_errors:
            self._filter_errors[key] = []
        self._filter_errors[key].append(e)
        return None

    def handle_exception(
        self,
        e: UncaughtException,
    ) -> None:
        self.handle_filter_error(e)
        self._has_exceptions = True
        return None
